'use client';
import {useEffect,useState} from 'react';
import {Dialog} from '@base-ui/react/dialog';
import {Printer,Download,Share2,X} from 'lucide-react';
import {dailyReceipt,receiptReading,type ReceiptResult} from '@/lib/receipt';
type Snapshot=ReturnType<typeof dailyReceipt>&ReturnType<typeof receiptReading>;
export default function ReceiptPrinter({result,question}:{result:ReceiptResult;question:string}){
 const [open,setOpen]=useState(false),[data,setData]=useState<Snapshot|null>(null),[done,setDone]=useState(false),[include,setInclude]=useState(false),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
 useEffect(()=>{if(!open)return;setDone(false);const timer=setTimeout(()=>setDone(true),window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:3100);return()=>clearTimeout(timer);},[open]);
 function start(){setData({...dailyReceipt(),...receiptReading(result,question)});setInclude(false);setMessage('');setOpen(true);}
 function sections(d:Snapshot){return [{title:'本次 · '+d.mode,text:d.lines.join('\n')},{title:'留给你的建议',text:d.advice},...(include&&question?[{title:'此刻的问题',text:question}]:[]),{title:'今日黄历',text:d.almanac?d.almanac.lunar+'\n宜 · '+d.almanac.yi.join('、')+'\n忌 · '+d.almanac.ji.join('、'):'今日黄历暂未收录'},{title:'每日灵签 · '+String(d.lot.number).padStart(2,'0')+' '+d.lot.title,text:d.lot.text}];}
 async function save(share=false){if(!data||saving)return;setSaving(true);setMessage('');try{
 await document.fonts.ready;const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');if(!ctx)throw Error('无法生成图片');const width=720,pad=64;ctx.font='26px sans-serif';const rows:{text:string;title:boolean}[]=[];
 for(const section of sections(data)){rows.push({text:section.title,title:true});for(const paragraph of section.text.split('\n')){let line='';for(const char of paragraph){if(ctx.measureText(line+char).width>width-pad*2){rows.push({text:line,title:false});line='';}line+=char;}if(line)rows.push({text:line,title:false});}rows.push({text:'',title:false});}
 canvas.width=width;canvas.height=330+rows.reduce((n,r)=>n+(r.title?58:43),0);ctx.fillStyle='#f7f3e9';ctx.fillRect(0,0,width,canvas.height);ctx.fillStyle='#405967';ctx.textAlign='center';ctx.font='32px serif';ctx.fillText('月匣 · 今日小票',width/2,75);ctx.font='20px sans-serif';ctx.fillText(data.date+'  /  北京时间',width/2,117);ctx.textAlign='left';let y=170;for(const row of rows){ctx.font=row.title?'bold 24px sans-serif':'26px sans-serif';ctx.fillStyle=row.title?'#607985':'#405967';ctx.fillText(row.text,pad,y);y+=row.title?58:43;}ctx.textAlign='center';ctx.font='18px sans-serif';ctx.fillText('月匣原创每日签 · 留住此刻的一点光',width/2,y+18);ctx.fillText('elijah-github-io.381391076.workers.dev',width/2,y+50);
 const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('生成失败')),'image/png'));const file=new File([blob],'月匣小票-'+data.date+'.png',{type:'image/png'});
 if(share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'月匣 · 今日小票'});setMessage('已打开分享');}else{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);setMessage(share?'小票已保存，可以发送给朋友。':'小票已保存');}
 }catch(e){if(!(e instanceof Error&&e.name==='AbortError'))setMessage('暂时未能保存，请再试一次。');}finally{setSaving(false);}}
 return <><button className="receipt-trigger" onClick={start}><Printer size={18}/><span>打印今日小票<small>把这一次的答案，带走</small></span><span aria-hidden="true">↗</span></button>
 <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Portal><Dialog.Backdrop className="receipt-backdrop"/><Dialog.Popup className="receipt-popup"><Dialog.Close className="receipt-close" aria-label="收起小票"><X size={20}/></Dialog.Close><Dialog.Title className="receipt-heading">留住，此刻的回响</Dialog.Title><Dialog.Description className="receipt-subheading">{done?'你的小票已打印完成':'正在为你打印今日小票…'}</Dialog.Description>
 {data&&<><div className={'receipt-machine '+(!done?'is-printing':'')}><div className="printer-top"><span>MOONBOX</span><i/><b>THERMAL · 01</b></div><div className="printer-slot"/><div className="printer-label">月匣便笺所 <span>● READY</span></div></div><div className="receipt-paper-window"><article className="receipt-paper"><header><span>✦</span><h3>今日小票</h3><p>{data.date} · 北京时间</p></header>{sections(data).map(s=><section key={s.title}><h4>{s.title}</h4><p>{s.text}</p></section>)}<footer><div className="receipt-barcode" aria-hidden="true"/><p>月匣原创每日签</p><p>留住此刻的一点光</p></footer></article></div>
 <div className="receipt-controls">{question&&<label><input type="checkbox" checked={include} onChange={e=>setInclude(e.target.checked)}/> 小票中带上我的问题</label>}<div><button disabled={!done||saving} onClick={()=>void save()}><Download size={16}/> 保存小票</button><button disabled={!done||saving} onClick={()=>void save(true)}><Share2 size={16}/> 分享</button></div><p role="status">{message||(!done?'纸张缓缓吐出，请稍候':'愿这一点提示，陪你走一小段路。')}</p></div></>}
 </Dialog.Popup></Dialog.Portal></Dialog.Root></>;
}
